config/routes.rb
Ejercicio1::Application.routes.draw do

  scope "/:locale", locale: /en|es/, defaults: {locale: "es"} do  
    delete 'session' => 'sessions#destroy'
    resources :sessions

    resources :users

    resources :orders

    resources :products
  end

  root 'sessions#login'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
	STATUS_OPTIONS = %w(Pendiente Enviado Recibido)
	PAYMENT_OPTIONS = %w(efectivo tarjeta paypal)

    validates :customer_name, :customer_surname, :delivery_address, :delivery_city, :payment_method, :order_status, presence: true
  	validates :order_status, :inclusion => {:in => STATUS_OPTIONS, :message => "must be one of the following: 'Pendiente' 'Enviado' 'Recibido'"}    
  	validates :payment_method, :inclusion => {:in => PAYMENT_OPTIONS, :message => "must be one of the following: 'efectivo' 'tarjeta' 'paypal'"}    

  	has_many :line_items, :dependent => :destroy
  	has_many :products, through: :line_items

	accepts_nested_attributes_for :line_items, reject_if: :all_blank, :allow_destroy => true
	
	before_validation :autocomplete_orderstatus, on: :create

	def get_total_price
		line_items.sum {|l| l.price * l.quantity}
	end

	protected
	def autocomplete_orderstatus
		self.order_status = "Pendiente"
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    1.times {@order.line_items.build}
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }

        OrderMailer.new_order_email(@order,current_user).deliver    

      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_status, :payment_method, :delivery_address, :delivery_city, :customer_name, :customer_surname, line_items_attributes:[:quantity, :product_id, :order_id, :price, :id, :_destroy])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', :model => Order.model_name.human, :count => @order.errors.count) %>:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:action] == "edit" %>
    <div class="field">
      <%= f.label :order_status %><br>
      <%= f.text_field :order_status %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment_method %><br>
    <%= f.text_field :payment_method %>
  </div>
  <div class="field">
    <%= f.label :delivery_address %><br>
    <%= f.text_field :delivery_address %>
  </div>
  <div class="field">
    <%= f.label :delivery_city %><br>
    <%= f.text_field :delivery_city %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :customer_surname %><br>
    <%= f.text_field :customer_surname %>
  </div>
  <div>
    <table class="items_table">
      <tr class="orderrow">
          <th colspan="3"><%= t "order.orderproducts"%></th>
      </tr>      
      <tr class="orderrow">
        <th><%= Product.human_attribute_name("product_name") %></th>
        <th><%= LineItem.human_attribute_name("quantity") %></th>
        <th><%= t "menu.actions"%></th>
      </tr>
      <%= f.fields_for :line_items do |builder| %>
        <%= render 'line_item_fields', :f => builder %>
      <% end %>       
      <tr><td colspan="3"><%= link_to_add_fields t("order.newline"), f, :line_items %></td></tr>      
    </table>
  </div>
  <div class="actions">
    <%= f.submit t("menu.save"), :class => 'btn btn-order'%>
  </div>
<% end %>

app/views/orders/_line_item.html.erb
<tr>
	<td><%=h line_item.product.product_name %></td>
  	<td class="centercell"><%=h line_item.quantity %></td>
  	<td class="centercell"><%=h number_to_currency(line_item.price, precision: 2, unit: "€") %></td>
</tr>  

app/views/orders/_line_item_fields.html.erb
<tr class="items">
	<td><%= f.collection_select :product_id, Product.all, :id, :product_with_category, { prompt: true }, { class: 'selectproduct' } %></td>
	<td class="centercell"><%= f.text_field :quantity %></td>
  	<td class="centercell">
  		<%= f.hidden_field :id %>
  		<%= f.hidden_field :_destroy %>
  		<%= link_to_function t("order.removeline"), "remove_line_item(this)" %>	
	</td>
</tr> 

app/views/orders/edit.html.erb
<div class="orderview">
	<h1><%= t "order.edit"%></h1>
</div>

<%= render 'form' %>

<div class="btn btn-order">
	<%= link_to t("menu.show"), @order %>
</div>
<div class="btn btn-order">
	<%= link_to t("menu.back"), orders_path %>
</div>

app/views/orders/index.html.erb
<div class="orderview">
  <h1><%= t "order.list"%></h1>
</div>

<table class="items_table">
  <thead>
    <tr class="orderrow">
      <th><%= Order.human_attribute_name("order_status")%></th>
      <th><%= Order.human_attribute_name("payment_method")%></th>
      <th><%= Order.human_attribute_name("delivery_address")%></th>
      <th><%= Order.human_attribute_name("delivery_city")%></th>
      <th><%= Order.human_attribute_name("customer_name")%></th>
      <th><%= Order.human_attribute_name("customer_surname")%></th>
      <th colspan="3"><%= t "menu.actions"%></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_status %></td>
        <td><%= order.payment_method %></td>
        <td><%= order.delivery_address %></td>
        <td><%= order.delivery_city %></td>
        <td><%= order.customer_name %></td>
        <td><%= order.customer_surname %></td>
        <td class="centercell"><%= link_to t("menu.show"), order_path(id: order.id) %></td>
        <td class="centercell"><%= link_to t("menu.edit"), edit_order_path(id: order.id) %></td>
        <td class="centercell"><%= link_to t("menu.destroy"), order_path(id: order.id), method: :delete, data: { confirm: t("messages.destroy") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn btn-order">
  <%= link_to t("menu.neworder"), new_order_path %>
</div>
<br>
<div class="btn btn-product">
  <%= link_to t("menu.newproduct"), new_product_path %>
</div>
<div class="btn btn-product">
  <%= link_to t("menu.products"), products_path %>
</div>

app/views/orders/new.html.erb
<div class="orderview">
	<h1><%= t "order.new"%></h1>
</div>

<%= render 'form' %>

<div class="btn btn-order">
	<%= link_to t("menu.back"), orders_path %>
</div>

app/views/orders/show.html.erb
<div class="orderview">
  <h1><%= t "order.details"%></h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= Order.human_attribute_name("order_status") %>:</strong>
  <%= @order.order_status %>
</p>

<p>
  <strong><%= Order.human_attribute_name("payment_method") %>:</strong>
  <%= @order.payment_method %>
</p>

<p>
  <strong><%= Order.human_attribute_name("delivery_address") %>:</strong>
  <%= @order.delivery_address %>
</p>

<p>
  <strong><%= Order.human_attribute_name("delivery_city") %>:</strong>
  <%= @order.delivery_city %>
</p>

<p>
  <strong><%= Order.human_attribute_name("customer_name") %>:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong><%= Order.human_attribute_name("customer_surname") %>:</strong>
  <%= @order.customer_surname %>
</p>

<table class="items_table">
  <tr class="orderrow">
      <th colspan="3"><%= t "order.orderproducts"%></th>
  </tr>
  <tr class="orderrow">
    <th><%= Product.human_attribute_name("product_name") %></th>
    <th><%= LineItem.human_attribute_name("quantity") %></th>
    <th><%= LineItem.human_attribute_name("price")%></th>
  </tr>
  <%= render @order.line_items %> 
  <tr>
    <td colspan="3" align="right">
        <%= label_tag(t("order.totalprice")) %>
        <%=h number_to_currency(@order.get_total_price, precision: 2, unit: "€") %>
    </td>
  </tr>
</table>

<br/>

<div class="btn btn-order">
  <%= link_to t("menu.edit"), edit_order_path(@order) %>
</div>
<div class="btn btn-order">
  <%= link_to t("menu.back"), orders_path %>
</div>