config/routes.rb
Ejercicio1::Application.routes.draw do

  scope "/:locale", locale: /en|es/, defaults: {locale: "es"} do  
    delete 'session' => 'sessions#destroy'
    resources :sessions

    resources :users

    resources :orders

    resources :products
  end

  root 'sessions#login'

  

end

app/models/product.rb
# encoding: utf-8
class Product < ActiveRecord::Base
	CATEGORY_OPTIONS = ['libros', 'música & películas', 'electrónica', 'hogar', 'juguetes', 'ropa', 'comestibles']

    validates :product_name, :added_at, :stock, :price, presence: true
	validates :stock, numericality: { only_integer: true}
	validates :price, numericality: { only_integer: false, greater_than:0}	
  	validates :category, :inclusion => {:in => CATEGORY_OPTIONS, :message => "must be one of the following: 'libros', 'música & películas', 'electrónica', 'hogar', 'juguetes', 'ropa', 'comestibles'"}
	validates :product_name, uniqueness: {case_sensitive: false }    

	has_many :line_items
  	has_many :orders, through: :line_items

  	scope :search_by_category, lambda{ |category| where("category = ?", category) if category.present? }  
  	scope :search_by_stock, lambda{ |stock| where("stock = ?", stock) if stock.present? }
  	scope :search_by_date, lambda{ |date1, date2| where(added_at:[date1...date2]) if date1.present? && date2.present? }
  	scope :search_by_manufacturer, lambda{ |manufacturer| where("manufacturer like ?", "%#{manufacturer}%") if manufacturer.present?}
  	scope :search_by_price, lambda{ |price1, price2| where(price:[price1...price2]) if price1.present? && price2.present? }

	def product_with_category
    	"#{product_name} - #{category}"
  	end
	
	def stock_movement(quantity)
		self.stock -= quantity
		update_column(:stock, self.stock)
	end
	
	def self.product_filters(params)
	    products = all
	    products = products.search_by_category(params[:category]).
	    search_by_stock(params[:stock]).
	    search_by_date(params[:date1],params[:date2]).
	    search_by_manufacturer(params[:manufacturer]).
	    search_by_price(params[:price1],params[:price2]) 		
	end 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.product_filters(params.slice(:category, :stock, :manufacturer, :date1, :date2, :price1, :price2))
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :description, :category, :added_at, :manufacturer, :stock, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', :model => Product.model_name.human, :count => @product.errors.count) %>:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :description  %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>  
  <div class="field">
    <%= f.label :added_at %><br>
    <%= f.datetime_select :added_at %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :price  %><br>
    <%= f.number_field :price %>
  </div>  
  <div class="actions">
    <%= f.submit t("menu.save"), :class => 'btn btn-product'%>
  </div>
<% end %>

app/views/products/_search_products.html.erb
<form action="<%= products_path %>" method="get" >
  <div class="searchbox">
    <h4><%= t("product.search") %></h4>
    <table>
      <tr>
        <td>
          <div class="field">
            <%= label_tag(Product.human_attribute_name("category")) %>:
          </div>
        </td>        
        <td>
          <div class="field">
            <input type="text" name="category" value="<%= params[:category] %>">
          </div>
        </td>
        <td>
          <div class="field">
            <%= label_tag(Product.human_attribute_name("stock")) %>:
          </div>
        </td>        
        <td>
          <div class="field">
            <input type="text" name="stock" value="<%= params[:stock] %>">
          </div>
        </td>
        <td>
          <div class="field">
            <%= label_tag(Product.human_attribute_name("manufacturer")) %>:
          </div>
        </td>                  
        <td>
          <div class="field">
            <input type="text" name="manufacturer" value="<%= params[:manufacturer] %>">
          </div>
        </td>          
      </tr>
      <tr>
        <td>
          <div class="field">
            <%= label_tag(Product.human_attribute_name("added_at")) %>:
          </div>
        </td>                
        <td>
          <div class="field">
            <input type="date" name="date1" value="<%= params[:date1] %>">
          </div>
        </td>        
        <td align="center">
          <div class="field">
            <%= label_tag(t("product.searchrange")) %>
          </div>
        </td>        
        <td>
          <div class="field">
            <input type="date" name="date2" value="<%= params[:date2] %>">
          </div>
        </td>        
        <td colspan="2">&nbsp;</td>
      </tr>
      <tr>
        <td>
          <div class="field">
            <%= label_tag(Product.human_attribute_name("price")) %>:
          </div>
        </td>        
        <td>
          <div class="field">
            <input type="number" name="price1" value="<%= params[:price1] %>">
          </div>
        </td>
        <td align="center">
          <div class="field">
            <%= label_tag(t("product.searchrange")) %>
          </div>
        </td>                        
        <td>
          <div class="field">
            <input type="number" name="price2" value="<%= params[:price2] %>">
          </div>
        </td>        
        <td colspan="2">&nbsp;</td>
      </tr>      
      <tr>
        <td colspan="6" align="right">
          <%= submit_tag t("product.search"), :class => 'btn btn-product'%>
        </td>
      </tr>
    </table>
  </div>
</form>

app/views/products/edit.html.erb
<div class="productview">
	<h1><%= t "product.edit"%></h1>
</div>

<%= render 'form' %>

<div class="btn btn-product">
	<%= link_to t("menu.show"), @product %>
</div>
<div class="btn btn-product">
	<%= link_to t("menu.back"), products_path %>
</div>

app/views/products/index.html.erb
<div class="productview">
  <h1><%= t "product.list"%></h1>
</div>

<%= render "search_products" %> 

<table class="items_table">
  <thead>
    <tr class="productrow">
      <th><%= Product.human_attribute_name("product_name") %></th>
      <th><%= Product.human_attribute_name("description") %></th>
      <th><%= Product.human_attribute_name("category") %></th>      
      <th><%= Product.human_attribute_name("added_at") %></th>
      <th><%= Product.human_attribute_name("manufacturer") %></th>
      <th><%= Product.human_attribute_name("stock") %></th>
      <th><%= Product.human_attribute_name("price") %></th>
      <th colspan="3"><%= t "menu.actions"%></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.description %></td>
        <td><%= product.category %></td>
        <td class="centercell"><%= product.added_at.to_formatted_s(:db) %></td>
        <td><%= product.manufacturer %></td>
        <td class="centercell"><%= product.stock %></td>
        <td class="centercell"><%= product.price %></td>
        <td class="centercell"><%= link_to t("menu.show"), product_path(id: product.id) %></td>
        <td class="centercell"><%= link_to t("menu.edit"), edit_product_path(id: product.id) %></td>
        <td class="centercell"><%= link_to t("menu.destroy"), product_path(id: product.id), method: :delete, data: { confirm: t("messages.destroy") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn btn-product">
  <%= link_to t("menu.newproduct"), new_product_path %>
</div>    
<br>
<div class="btn btn-order">
  <%= link_to t("menu.neworder"), new_order_path %>
</div>
<div class="btn btn-order">
  <%= link_to t("menu.orders"), orders_path %>
</div>

app/views/products/new.html.erb
<div class="productview">
	<h1><%= t "product.new"%></h1>
</div>

<%= render 'form' %>

<div class="btn btn-product">
	<%= link_to t("menu.back"), products_path %>
</div>

app/views/products/show.html.erb
<div class="productview">
  <h1><%= t "product.details"%></h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= Product.human_attribute_name("product_name")%>:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong><%= Product.human_attribute_name("description") %>:</strong>
  <%= @product.description %>
</p>

<p>
  <strong><%= Product.human_attribute_name("category") %>:</strong>
  <%= @product.category %>
</p>

<p>
  <strong><%= Product.human_attribute_name("added_at") %>:</strong>
  <%= @product.added_at %>
</p>

<p>
  <strong><%= Product.human_attribute_name("manufacturer") %>:</strong>
  <%= @product.manufacturer %>
</p>

<p>
  <strong><%= Product.human_attribute_name("stock") %>:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong><%= Product.human_attribute_name("price") %>:</strong>
  <%= @product.price %>
</p>

<div class="btn btn-product">
  <%= link_to t("menu.edit"), edit_product_path(@product) %>
</div>
<div class="btn btn-product">
  <%= link_to t("menu.back"), products_path %>
</div>